/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as TimerImport } from './routes/timer'
import { Route as FolderStructureImport } from './routes/folder-structure'
import { Route as CommentBoxImport } from './routes/comment-box'
import { Route as CarouselImport } from './routes/carousel'
import { Route as BarChartImport } from './routes/bar-chart'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const TimerRoute = TimerImport.update({
  path: '/timer',
  getParentRoute: () => rootRoute,
} as any)

const FolderStructureRoute = FolderStructureImport.update({
  path: '/folder-structure',
  getParentRoute: () => rootRoute,
} as any)

const CommentBoxRoute = CommentBoxImport.update({
  path: '/comment-box',
  getParentRoute: () => rootRoute,
} as any)

const CarouselRoute = CarouselImport.update({
  path: '/carousel',
  getParentRoute: () => rootRoute,
} as any)

const BarChartRoute = BarChartImport.update({
  path: '/bar-chart',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/bar-chart': {
      id: '/bar-chart'
      path: '/bar-chart'
      fullPath: '/bar-chart'
      preLoaderRoute: typeof BarChartImport
      parentRoute: typeof rootRoute
    }
    '/carousel': {
      id: '/carousel'
      path: '/carousel'
      fullPath: '/carousel'
      preLoaderRoute: typeof CarouselImport
      parentRoute: typeof rootRoute
    }
    '/comment-box': {
      id: '/comment-box'
      path: '/comment-box'
      fullPath: '/comment-box'
      preLoaderRoute: typeof CommentBoxImport
      parentRoute: typeof rootRoute
    }
    '/folder-structure': {
      id: '/folder-structure'
      path: '/folder-structure'
      fullPath: '/folder-structure'
      preLoaderRoute: typeof FolderStructureImport
      parentRoute: typeof rootRoute
    }
    '/timer': {
      id: '/timer'
      path: '/timer'
      fullPath: '/timer'
      preLoaderRoute: typeof TimerImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  AboutRoute,
  BarChartRoute,
  CarouselRoute,
  CommentBoxRoute,
  FolderStructureRoute,
  TimerRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/bar-chart",
        "/carousel",
        "/comment-box",
        "/folder-structure",
        "/timer"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/bar-chart": {
      "filePath": "bar-chart.tsx"
    },
    "/carousel": {
      "filePath": "carousel.tsx"
    },
    "/comment-box": {
      "filePath": "comment-box.tsx"
    },
    "/folder-structure": {
      "filePath": "folder-structure.tsx"
    },
    "/timer": {
      "filePath": "timer.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
